#!/bin/bash
# Copyright 2026 AzoraLabs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Builds and runs this Azora Engine project.
# Generated by Azora Studio from a project template of the __AZORA_LIBRARY_ID__ library.
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
LIB_DIR="${AZORA_ENGINE_HOME:-$HOME/.azora/libraries/__AZORA_LIBRARY_ID__/__AZORA_LIBRARY_VERSION__}"

if [ ! -d "$LIB_DIR" ]; then
    echo "error: Azora Engine library not found at $LIB_DIR" >&2
    echo "Install the library in Azora Studio (Libraries) or set AZORA_ENGINE_HOME." >&2
    exit 1
fi

exec sh "$LIB_DIR/tools/build.sh" "$PROJECT_DIR" "${1:-run}"
